### ISSUE TITLE
Enforce strict config unmarshalling

### ISSUE THREAD

**Issue by mlevesquedion** [google/go-flow-levee#206]
In order to minimize the risk of configuration errors, we would like the unmarshalling of the configuration to be strict. Specifically, it should disallow unknown fields in matchers. This avoids errors where a typo in a key name leads to an incorrect configuration. We don't want typos to lead to silent failures, e.g. a matcher is broken and the user thinks their code is safe when it is not.

There are already two test cases covering this behavior to some extent, in `config/matcher_test.go`:

```go
		{
			desc: "Unmarshaling is strict",
			yaml: `
Blahblah: foo
PackageRE: bar`,
			shouldErrorOnLoad: false, // TODO true
		},
```

(It is the same case, in the tests for two different matchers.)

**Comment by benhxy** [comment]
@mlevesquedion Does this basically boil down to these rules?
If it's a funcMatcher, then only allow package, packageRE, receiver, receiverRE, method, methodRE.
If it's a sourceMatcher, then only allow package, packageRE, type, typeRE, field, fieldRE.

**Comment by mlevesquedion** [comment]
Those would be the main rules to enforce, yes! We would also like the matching for FieldTags to be strict:

```yaml
FieldTags:
  - Key: levee
    Val: source
```

More generally, anywhere that the config yaml contains a field that we can't represent in our internal config, that's an error.
