### ISSUE TITLE
Proposal for testdata convention - spoof source root with go.mod to assist IDEs

### ISSUE THREAD

**Issue by PurelyApplied** [google/go-flow-levee#274]
## Problem statement

`analysistest` expects `testdata` to be a fake ~~GOROOT~~GOPATH.  We currently have various tests at `.../testdata/src/example.com/...` to test the various analyzers.

IntelliJ expects our project to be configured with Go modules.  This fake root is opaque to IntelliJ.  As a consequence, the IDE can't resolve the linkage for packages within `testdata`.  E.g.,

![image](https://user-images.githubusercontent.com/7175687/106337453-12f1c780-6246-11eb-9480-fd2999df26d8.png)

This conflict makes development in of tests sticker than it needs to be.  Additionally, while I believe I'm the only one who does this, but it also prevents general execution of an analyzer from the command-line.  I am partial to using `ssadump` when investigating issues, but this is prevented in any file with an unresolved import.

## Proposal

I propose adding a trivial `go.mod` to each `testdata/src/<some shared root>` so that our IDEs can resolve these paths.  See #273 and associated branch for an example within `config/testdata`.  This allows proper linking within IntelliJ while retaining test compatability.

For compatability with the builder within `analysistest`, we would each `testdata/src/...` to be self-contained.  Cross-package imports are permitted, but not cross-module imports.  This requires a shared root within `testdata/src/`.  #273 demonstrates this as `testdata/src/github.com/`.  In practice, we should avoid collision of go modules and adopt adopt `testdata/src/<identifier>`, e.g. `testdata/src/levee_configtest/...`.

I'd love to hear your thoughts about adding this as a convention going forward.  At your convenience, please pull my `pseudo-module-testing` branch and see if this works with your own workflow.  (I had to execute `config_test` to trigger compiling and linkage.)

**Comment by mlevesquedion** [comment]
> analysistest expects testdata to be a fake GOROOT.

AFAIU `analysistest` takes whatever `dir` we give it (typically `testdata`) and makes that the `GOPATH`:
```go
Env:   append(os.Environ(), "GOPATH="+dir, "GO111MODULE=off", "GOPROXY=off"),
```

> Additionally, while I believe I'm the only one who does this, but it also prevents general execution of an analyzer from the command-line.

I've tried to do this a bunch of times. Most often I want to run levee itself on a directory under testadata. Sometimes `ssadump` too, e.g. it would be useful to be able to watch a test file I'm editing an see the SSA be regenerated live.

---

I like the idea of making test files easier to edit. I'll make more comments on the PR itself.

**Comment by PurelyApplied** [comment]
Whoops.  It looks like I misplaced the `go.mod` file.  It should be in `.../testdata/src/github.com` rather than the `.../src/`.  When I was cleaning up the example PR, IntelliJ must've been holding linkage in the cache and not cared that I moved the module file.

Thanks for the early investigation.  Maybe the updated PR this one will work for you, like it does for me:


![](https://screenshot.googleplex.com/7wSuC7NqHweW6ce.png)

**Comment by mlevesquedion** [comment]
Looks ok on my end. This is great!

**Comment by PurelyApplied** [comment]
Glad it's not dependent on some weird config specific to my workflow!

To formalize the convention, do you have any input as to how we should name things?  I was thinking that the root "package" that the `go.mod` spoofs should mirror the test file where it's going to be consumed.  For instance, the files consumed by analyzer tests in `config_test.go` would correspond to files in `.../testdata/src/config_test/**`.  The `go.mod` would need to live in that `src/config_test/` root.

I haven't tested it yet, but I do believe we'll want to have the various `src/<synthetic root>` have distinct names.  I'm not sure how an IDE would handle a collision if we had multiple modules defining the same (e.g.,) `example.com`.

**Comment by mlevesquedion** [comment]
That sounds fine to me. I don't have a hard preference concerning what the exact directory hierarchy should look like, as long as we can run the tests and the package resolution works.

**Comment by benhxy** [comment]
This sounds great. Not seeing all the red in IDE is a quality of life improvement!
