### ISSUE TITLE
false negative when analyze the url parameters about gin framework

### ISSUE THREAD

**Issue by 4huo** [google/go-flow-levee#311]
## False negative report

Use this issue template to describe a situation where the analyzer failed to recognize that a piece of unsafe code is unsafe. For example, if the analyzer did not produce a report on the following piece of code, then that would be a false negative:

```go
func ginhandler(c *gin.Context) {
	name := c.Query("name") // url parameter name set to source
	c.String(200, name)
	log.Println(name) //sink
}

func test123() {
	r := gin.Default()
	r.GET("/hello", ginhandler)
	r.Run()
}
```
(We are assuming that `Source` has been configured as a source and `Sink` has been configured as a sink.)

**Describe the issue**
Please include a clear and concise description of what happened and why you think it is a false negative.
I hava configured the levee and did some tests. It is ok with net/http.Form setted as source and log.Println as sink. However when I test the code I showed, levee can't recognize it as an unsafe case.

**To Reproduce**
Please make it as easy as possible for us to reproduce what you observed. If possible, provide the exact configuration and code on which the analyzer failed to produce a report. If the code cannot be shared, please provide a simplified example and confirm that it also contains the false negative.

config file
`
{
  "Sources": [
    {
      "PackageRE": "github.com/gin-gonic/gin",
      "TypeRE": "Context",
      "FieldRE": ""
    }
  ],
  "Sinks": [
    {
      "PackageRE": "^log$",
      "MethodRE": "Print"
    }
  ]

}
`

command: levee -config=config.json example.go

**Additional context**

The main point here is that I want to do some analysis on the url parameters' taint, especially the gin framework, thanks for your time to help me with this.

**Comment by mlevesquedion** [comment]
Hello @4huo!

Sorry for the late reply, it seems I missed the notification.

Thank you for your report! If I understand correctly, since you identified the `Context` type as a source, you are expecting the value returned by `c.Query("name")` (where `c` is `c *gin.Context`) to be tainted. Can you confirm this? Is it just the `"name"` key you are worried about, or anything returned by `c.Query`? Are you expecting other methods to also return tainted values?

Also, can you tell me what version of the analyzer you used, ideally a git commit SHA if possible? (e.g., if you built from source, or if you used `git install` or `go get` with a `go.mod` file). If that's not available, do you have a rough idea of when you installed the analyzer?

**Comment by 4huo** [comment]
> Hello @4huo!
> 
> Sorry for the late reply, it seems I missed the notification.
> 
> Thank you for your report! If I understand correctly, since you identified the `Context` type as a source, you are expecting the value returned by `c.Query("name")` (where `c` is `c *gin.Context`) to be tainted. Can you confirm this? Is it just the `"name"` key you are worried about, or anything returned by `c.Query`? Are you expecting other methods to also return tainted values?
> 
> Also, can you tell me what version of the analyzer you used, ideally a git commit SHA if possible? (e.g., if you built from source, or if you used `git install` or `go get` with a `go.mod` file). If that's not available, do you have a rough idea of when you installed the analyzer?

**Comment by 4huo** [comment]
Thanks for replying. Yes, I would expect the value returned by c.Query("name") and I am worried about all returned by c.Query cause I want to get any input from url parameter which pass to some sink points.

I used go get with a go.mod file to get binarey file and I installed it about ten days ago.

And Sir, I was wondering if you could reproduce this scene I showed.Is my configure file wrong or somethings wired happens? I truely want to understand how levee works and learn to do some developing.

**Comment by 4huo** [comment]
Thanks very much. That makes sense and I get it. I think I should read some code of levee and try to understand its main concept.
