### ISSUE TITLE
Enable specification of analysis scope

### ISSUE THREAD

**Issue by PurelyApplied** [google/go-flow-levee#88]
Currently, analysis is executed on all provided packages, as well as the transitive closure of all Go package dependencies.

A user may consider third-party packages, generated code to be out-of-scope, or specifically sanctioned packages out of scope for analysis.  While upstream analysis on these may be necessary (e.g. `buildssa`), we should bypass our analysis of such specified packages as much as possible.

Ideally, this bypass should occur prior to entry into the various `analyzer.Analyzer`s to reduce the size of the transitive dependency graph.

**Comment by mlevesquedion** [comment]
For performance reasons I agree that we will likely want to avoid analyzing anything we don't have to, but if for whatever reason we *have* to analyze everything, we could just avoid _producing reports_ for violations that are out of scope.

**Comment by mlevesquedion** [comment]
I think with the `Exclude` field we now have adequate support for this feature.
